version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: ${APP_PATH_CONTAINER}
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "70:80"
            - "443:443"
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mariadb
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: admin
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    #Composer Service
#    composer:
#        image: composer
#        volumes:
#            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
#        working_dir: ${APP_PATH_CONTAINER}
#        command: composer install

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
