version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: ${APP_PATH_CONTAINER}
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - redis

    #Redis Service
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - ${DB_PATH_HOST}:/data

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "70:80"
            - "443:443"
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
            - .docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mariadb
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: admin
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql/
            - .docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    #RabbitMQ Service
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - .docker/rabbitmq/data/:/var/lib/rabbitmq/
            - .docker/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
